### PR TITLE
Ignore closed issues in triage query

### PR DESCRIPTION
**Pull request by mandre**

### CODE REVIEW

**Review by pierreprinetti — APPROVED** [review]

**Review by stephenfin — COMMENTED** [review]
Is this command even running yet? We haven't merged the patch. Or do the pre-merge tests actually run the things?

**Comment by mandre** [comment]
> Is this command even running yet? We haven't merged the patch. Or do the pre-merge tests actually run the things?

The pj-rehearse on your release patch ran it.

**Comment by pierreprinetti** [comment]
I put a hold because it crossed my mind that the triage bot is un-triaging when the "test-coverage" flag is unset. And that one should be set for all closed bugs. I suggest that we close this PR and go back setting `Triaged` to our closed bugs :)

**Pull request closed without merging**
