### PR TITLE
Fix nil pointer dereference in priorityCheck function

### PR DESCRIPTION
**Pull request by dkokkino**
Added a conditional check to handle cases where the resolution field is nil, preventing potential nil pointer dereference. The string returned in the error message might need to be updated

### CODE REVIEW

**Comment by pierreprinetti** [comment]
This is not quite right. If Resolution is nil, then we want to check the priority. In other words, we only check for the contents of Resolution if Resolution is not nil.

We started checking Resolution because in some cases, we want to skip checking for Priority (e.g. when the bug is “Won’t Do” or “Cannot reproduce” etc). In case Resolution is nil, we don’t want to skip the Priority check.

**Comment by stephenfin** [comment]
Also, seeing as we're reviewing, it would be good to put the contents of your PR summary into the commit message. That way, `git log` is actually useful.

Also, this is a nit, but if you could phrase in the imperative mood, that would be :ok_hand: Instead of:

> Added a conditional check...

Try:

> Add a conditional check...

i.e. the thing the patch *will do* if applied, not the thing it *has done* (since it doesn't do anything until it's applied :smile:)

There are a million "good commit message" articles but this one looks reasonable to me https://cbea.ms/git-commit/

**Comment by dkokkino** [comment]
@pierreprinetti I understand my mistake. Thank you for clarifying it.

**Comment by dkokkino** [comment]
@stephenfin Thank you for your feedback! I will definitely try to improve my commit messages.

**Comment by pierreprinetti** [comment]
That's more like it! Thank you.

Please run `go fmt ./...` and squash, and this is ready!

**Comment by stephenfin** [comment]
Looks like you need to squash these commits still. You can do this with `git-rebase` like so.

First, ensure your `main` branch is up-to-date:

```
git checkout main
git pull
```

Then switch to your "development" branch and rebase onto `main`:

```
git checkout fix-nil-pointer-priorityCheck
git rebase -i main
```

This will open an editor with a "file" that looks like this:

```
pick 97b90cc Added fix for nil-pointer bug relating to Resolution                                                                                                                                                                                                                                                                                                                                                                       
pick 53a26b1 Fix issue in initial PR #82                                                                                                                                                                                                                                                                                                                                                                                                
pick 1f67494 Add conditional check to handle nil-pointer 

# Rebase 2f28cbd..1f67494 onto 2f28cbd (3 commands)
#
# Commands:
# ...
```

This is ordered in chronological order, with the oldest commits first. Leave the first line as `pick`, but replace `pick` with `fixup` (or just `f`) on the other 2 lines:

```
pick 97b90cc Added fix for nil-pointer bug relating to Resolution                                                                                                                                                                                                                                                                                                                                                                       
f 53a26b1 Fix issue in initial PR #82                                                                                                                                                                                                                                                                                                                                                                                                
f 1f67494 Add conditional check to handle nil-pointer 
```

Then save and exit. As the comments in the rebase suggest, `fixup` causes a commit to be merged into the preceding commit, so `53a26b1` will get merged into `97b90cc`, and `1f67494` will get merged into the merge of `53a26b1` + `97b90cc`.

If you mess up, you can use `git-reflog` to get back your old commits. Or you can simply write down the commit ID of the branch pre-rebase and use `git reset --hard <that_commit_id>` if needed.

**Pull request merged**
