### PR TITLE
Update the default bug assignee

### PR DESCRIPTION
**Pull request by pierreprinetti**
Caused by https://issues.redhat.com/browse/DPP-8569

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by EmilienM** [comment]
The query reports empty results but it contains the right flags for search.

**Comment by mandre** [comment]
> The query reports empty results but it contains the right flags for search.

The query result shows one bz:
https://bugzilla.redhat.com/buglist.cgi?bug_status=__open__&f1=component&f10=component&f11=component&f12=component&f13=CP&f15=CP&f17=CP&f18=keywords&f19=assigned_to&f2=OP&f3=rh_sub_components&f4=rh_sub_components&f5=rh_sub_components&f6=rh_sub_components&f7=OP&f8=short_desc&f9=OP&j2=OR&j9=OR&list_id=12170769&o1=notequals&o10=equals&o11=equals&o12=equals&o18=nowords&o19=equals&o3=equals&o4=equals&o5=equals&o6=equals&o8=anywords&query_format=advanced&v1=Documentation&v10=Installer&v11=Machine%20Config%20Operator&v12=Cloud%20Compute&v18=Triaged&v19=shiftstack-bugwatcher%40redhat.com&v3=OpenShift%20on%20OpenStack&v4=OpenStack%20CSI%20Drivers&v5=OpenStack%20Provider&v6=platform-openstack&v8=osp%20openstack

**Pull request merged**
