### PR TITLE
Makefile: Run pretriage locally

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
Cool, is the idea to help debugging the different commands, or rather kick a manual pre-triage when needed?

If that is for debugging, perhaps we could also introduce a dry-run mode that does not write to jira or send notifications, WDYT?

**Comment by pierreprinetti** [comment]
It's really for running it locally. The CI is broken at the moment and I needed a quick way to run the pretriage

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
